name: Django CI

on:
  push:
    tags:        
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FSTHUB_VER: ${{ github.ref_name }}
      BUILD_COMPOSE: docker/docker-compose.yml
    steps:
    - uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3.6.0
      with:
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker images
      run: |
        docker compose -f ${BUILD_COMPOSE} build app
        docker compose -f ${BUILD_COMPOSE} build server

    - name: Run app tests inside Docker
      run: |
        docker compose -f ${BUILD_COMPOSE} run \
          --entrypoint='bash' --rm \
          app \
          -c 'python3 manage.py test -v 2'

    - name: Push Docker images
      run: |
        docker compose -f ${BUILD_COMPOSE} push app server
